export const QUERY_KEY = {
  courses: 'courses',
  user: 'user',
  popular_courses: 'popular_courses',
  popular_study_materials: 'popular_study_materials',
  org_study_materials: 'org_study_materials',
  courses_by_institutionId: 'courses_by_institutionId',
  departments_by_facultyId: 'departments_by_facultyId',
  institutions: 'institutions',
  faculties: 'faculties',
  create_study_material: 'create_study_material',
  faculties_by_institution_id: 'faculties_by_institution_id',
  create_test: 'create_test',
  my_uploads: 'my_uploads',
  test_by_id: 'test_by_id',
  contributions: 'contributions',
  summary: 'summary',
  team_members: 'team_members',
  test_analysis_by_id: 'test_analysis_by_id',
  test_statistics: 'test_statistics',
  test_response_summary: 'test_response_summary',
  questions_by_id: 'questions_by_id',
};
